### ISSUE TITLE
Wrong content typetext/xml

### ISSUE THREAD

**Issue by vmavromatis** [hotelbeds-sdk/hotel-api-sdk-java#33]
Error when parsing unformatted response: 
```java
import com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient;
import com.hotelbeds.distribution.hotel_api_sdk.types.HotelApiSDKException;
import com.hotelbeds.hotelcontentapi.auto.messages.*;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class ContentFacilityTypologies {

    public static void main(String[] args) {
        // Perform the request and browse the results
        try (final HotelApiClient apiClient = new HotelApiClient("xxxxxxx", "xxxxxxx" )) {
            apiClient.setReadTimeout(20000);
            apiClient.init();

            for (FacilityType element : apiClient.getAllFacilityTypes("ENG", false)) {
                System.out.println(element);
            }

        } catch (HotelApiSDKException e) {
            log.error("Error requesting content", e);

        }
    }

}
```

Error:
```
20171207 11:19:27 ERROR-  - ContentElementSpliterator - Error retrieving list of elements
HotelApiSDKException(error=HotelbedsError(code=Invalid response, message=Wrong content typetext/xml))
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteContentAPI(HotelApiClient.java:952)
	at com.hotelbeds.distribution.hotel_api_sdk.ContentElementSpliterator.getElementBlock(ContentElementSpliterator.java:88)
	at com.hotelbeds.distribution.hotel_api_sdk.ContentElementSpliterator.<init>(ContentElementSpliterator.java:72)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.getAllElements(HotelApiClient.java:765)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.getAllFacilityTypes(HotelApiClient.java:679)
	at com.hotelbeds.demo.simple.ContentFacilityTypologies.main(ContentFacilityTypologies.java:45)
```

**Comment by Verdoso** [comment]
Hi @vmavromatis,
The "code=Invalid response, message=Wrong content typetext/xml)" seems to tell us that there is something wrong with the response, as it is not proper XML. The Hotelbeds backend should return XML even in case of error, so that usually means there is some communication error and the usual suspect in this case is the Authentication Gateway, as when you have an overquota error, an expired ApiKey or something like that, the answer it sends back is not XML but plain HTML and that makes the SDK barf.

That's one of the things I did not have time improving 😄 

The next step would be to enable full logging for the communication and you will be able to see the response that is being returned and proceed from there. To see all the traffic between the client and the backend set the log level of the class com.hotelbeds.distribution.hotel_api_sdk.helpers.LoggingRequestInterceptor to TRACE and you'll get the response in logs.

Cheers!

**Comment by vmavromatis** [comment]
Yes this was just a case of 403, we already have an issue exactly for improving that, when I get the time I will improve the error handling #14
